### ISSUE TITLE
Error when trying to use Bluetooth

### ISSUE THREAD

**Issue by thvasilo** [rootkiwi/an2linuxserver#12]
I get the following error when I try to start the program with Bluetooth enabled:

> Traceback (most recent call last):
  File "/home/tvas/.local/lib/python3.5/site-packages/bluetooth/bluez.py", line 240, in advertise_service
    protocols)
_bluetooth.error: (2, 'No such file or directory')
 During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
  File "an2linuxserver.py", line 779, in <module>
    bluetooth_server = ThreadingBluetoothServer()
  File "an2linuxserver.py", line 279, in __init__
    profiles=[SERIAL_PORT_PROFILE])
  File "/home/tvas/.local/lib/python3.5/site-packages/bluetooth/bluez.py", line 242, in advertise_service
    raise BluetoothError (str (e))
bluetooth.btcommon.BluetoothError: (2, 'No such file or directory')

I've tried various solutions regarding bluez from SO and others but couldn't get it to work.

**Comment by thvasilo** [comment]
Fixed by using updated README from this fork: https://github.com/mfossen/an2linuxserver/commits/master
