### ISSUE TITLE
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by kuvaldini** [rootkiwi/an2linuxserver#74]
```
> ./an2linuxserver.py
/home/kyb/devel/an2linuxserver/./an2linuxserver.py:778: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  ssl.SSLContext(protocol=ssl.PROTOCOL_TLSv1_2).load_cert_chain(CERTIFICATE_PATH,
2022-01-07 19:15:00.026 root         INFO     Server certificate fingerprint: E8 E0 B3 6A DF 83 F3 6A 1B 3C C2 EE 8C 48 68 89 22 61 DA 2A 8B 08 F9 56 7A 0E B8 63 51 DB 80 50 (an2linuxserver.py:826)
/home/kyb/devel/an2linuxserver/./an2linuxserver.py:836: DeprecationWarning: ssl.PROTOCOL_TLSv1_2 is deprecated
  notif_tls_ctx = ssl.SSLContext(protocol=ssl.PROTOCOL_TLSv1_2)
2022-01-07 19:15:00.026 root         INFO     (TCP) Waiting for connections on port 46352 (an2linuxserver.py:850)
Traceback (most recent call last):
  File "/home/kyb/devel/an2linuxserver/./an2linuxserver.py", line 874, in <module>
    bluetooth_server = ThreadingBluetoothServer()
  File "/home/kyb/devel/an2linuxserver/./an2linuxserver.py", line 284, in __init__
    advertise_service(self.bluetooth_server_sock, "AN2Linux_bluetooth_server",
  File "/usr/lib/python3.10/site-packages/bluetooth/bluez.py", line 271, in advertise_service
    _bt.sdp_advertise_service (sock._sock, name, service_id, \
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
```

CONFIG is default except bluetooth_server = on
```
[tcp]
tcp_server = on
tcp_port = 46352

[bluetooth]
bluetooth_server = on

# bluetooth_support_kitkat: enable bluetooth support for android 4.4 kitkat
# this setting is important for everyone using bluetooth
# you need to set this setting correctly otherwise it will not work
# if you are using android 4.4 kitkat this needs to be turned on
# because some cipher versions are not supported until after kitkat
# if you are using android 5.0+ you need to keep this setting off
bluetooth_support_kitkat = off

[notification]
# notification_timeout: display notification for this many seconds
# set 0 to never expire
# this setting might be completely ignored by your notification server
notification_timeout = 5

# list_size_duplicates: number of latest notifications to keep
# integer 0-50, if a notification is in this list it will not be shown
# set to 0 to disable
list_size_duplicates = 0

# ignore_duplicates_list_for_titles: notification titles that ignore duplicates list
# comma-separated, case-sensitive
ignore_duplicates_list_for_titles = AN2Linux, title

# keywords_to_ignore: do not show notifications that include these keywords in the notification titles
# comma-separated, case-sensitive. leading and trailing whitespace will be stripped.
keywords_to_ignore = 

# regexes_to_ignore: do not show notifications who's contents or title match the following regexes
regexes_to_ignore_in_title = 
regexes_to_ignore_in_content = 
```

**Comment by 321pranay** [comment]
The issue is with pybluez as the last release version is not compatible with python 3.10. The master branch ( https://github.com/pybluez/pybluez ) of pybluez is updated with the fix. You can try that.
